In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/blackjack_dataset_clean.csv")

display(df.head())
df.info()

,Unnamed: 0,shoe_id,cards_remaining,dealer_up,player_hand,player_final_action_value,action,run_count,true_count,win
0,0,749782,79,4,"[8, 10]",18,S,-6,-3,2
1,1,401890,281,9,"[10, 9]",19,S,-11,-2,0
2,2,582076,398,9,"[10, 11]",21,S,2,0,2
3,3,3982,299,9,"[7, 8]",15,H,12,2,1
4,4,358698,259,8,"[10, 4]",14,H,2,0,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694352 entries, 0 to 694351
Data columns (total 10 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Unnamed: 0                 694352 non-null  int64
 1   shoe_id                    694352 non-null  int64
 2   cards_remaining            694352 non-null  int64
 3   dealer_up                  694352 non-null  int64
 4   player_hand                694352 non-null  object
 5   player_final_action_value  694352 non-null  int64
 6   action                     694352 non-null  object
 7   run_count                  694352 non-null  int64
 8   true_count                 694352 non-null  int64
 9   win                        694352 non-null  int64
dtypes: int64(8), object(2)
memory usage: 53.0+ MB

In [4]:
df['action'].unique()

# HABRÍA QUE HACER UN STRIP EN EL PREPROCESADO??

array(['S', 'H', 'N', 'P', 'D', 'R', ' H', ' S', ' D'], dtype=object)

In [5]:
df['action'] = df['action'].str.strip()
df['action'].unique()

array(['S', 'H', 'N', 'P', 'D', 'R'], dtype=object)

In [6]:
df = df.drop(columns=["Unnamed: 0", "shoe_id"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694352 entries, 0 to 694351
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   cards_remaining            694352 non-null  int64
 1   dealer_up                  694352 non-null  int64
 2   player_hand                694352 non-null  object
 3   player_final_action_value  694352 non-null  int64
 4   action                     694352 non-null  object
 5   run_count                  694352 non-null  int64
 6   true_count                 694352 non-null  int64
 7   win                        694352 non-null  int64
dtypes: int64(6), object(2)
memory usage: 42.4+ MB

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694352 entries, 0 to 694351
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   cards_remaining            694352 non-null  int64
 1   dealer_up                  694352 non-null  int64
 2   player_hand                694352 non-null  object
 3   player_final_action_value  694352 non-null  int64
 4   action                     694352 non-null  object
 5   run_count                  694352 non-null  int64
 6   true_count                 694352 non-null  int64
 7   win                        694352 non-null  int64
dtypes: int64(6), object(2)
memory usage: 42.4+ MB

In [8]:
df.head()

,cards_remaining,dealer_up,player_hand,player_final_action_value,action,run_count,true_count,win
0,79,4,"[8, 10]",18,S,-6,-3,2
1,281,9,"[10, 9]",19,S,-11,-2,0
2,398,9,"[10, 11]",21,S,2,0,2
3,299,9,"[7, 8]",15,H,12,2,1
4,259,8,"[10, 4]",14,H,2,0,1

In [9]:
import ast

def sacar_columnas(df):

  # Convertir los strings a listas reales
  if isinstance(df["player_hand"].iloc[0], str):
      manos_listas = df["player_hand"].apply(ast.literal_eval)
  else:
      manos_listas = df["player_hand"]

  # Hacer un df con la serie de listas
  df_cartas = pd.DataFrame(manos_listas.tolist(), index=df.index)

  # Renombrar las columnas de 0-7 a carta_1-carta_8
  df_cartas.columns = [f"carta_{i+1}" for i in range(df_cartas.shape[1])]

  # Sustituir NaN por 0
  df_cartas = df_cartas.fillna(0).astype(int)

  # Juntar las 8 columnas y borrar 'player_hand'
  df = pd.concat([df, df_cartas], axis=1).drop(columns=["player_hand"])

  return df

In [10]:
df = sacar_columnas(df)

In [11]:
df

,cards_remaining,dealer_up,player_final_action_value,action,run_count,true_count,win,carta_1,carta_2,carta_3,carta_4,carta_5,carta_6,carta_7,carta_8
0,79,4,18,S,-6,-3,2,8,10,0,0,0,0,0,0
1,281,9,19,S,-11,-2,0,10,9,0,0,0,0,0,0
2,398,9,21,S,2,0,2,10,11,0,0,0,0,0,0
3,299,9,15,H,12,2,1,7,8,0,0,0,0,0,0
4,259,8,14,H,2,0,1,10,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694347,174,10,17,H,14,4,2,6,11,0,0,0,0,0,0
694348,174,10,12,H,14,4,2,6,11,5,0,0,0,0,0
694349,174,10,21,S,14,4,2,6,11,5,9,0,0,0,0
694350,142,6,8,H,1,0,2,6,2,0,0,0,0,0,0
694351,142,6,13,S,1,0,2,6,2,5,0,0,0,0,0

In [12]:
df.iloc[475919]

cards_remaining              258
dealer_up                     10
player_final_action_value     17
action                         S
run_count                      1
true_count                     0
win                            1
carta_1                        3
carta_2                       11
carta_3                        3
carta_4                       11
carta_5                        5
carta_6                        2
carta_7                       11
carta_8                       11
Name: 475919, dtype: object

In [13]:
# df = df.drop(columns="player_hand")
# df

In [15]:
# from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["target_action"] = encoder.fit_transform(df["action"])

# columnas_x = [
#     "cards_remaining",
#     "dealer_up",
#     "player_final_action_value",
#     "run_count",
#     "true_count",
#     "carta_1",
#     "carta_2",
#     "carta_3",
#     "carta_4",
#     "carta_5",
#     "carta_6",
#     "carta_7",
#     "carta_8",
# ]

# X = df[columnas_x]
# y = df["target_action"]

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# import xgboost as xgb

# modelo_blackjack = xgb.XGBClassifier(
#     objective="multi:softprob",  # Multiclase con probabilidad
#     num_class=6,  # Las accciones posibles ('S', 'H', 'N', 'P', 'D', 'R')
#     n_estimators=150,
#     learning_rate=0.1,
#     max_depth=6,
#     tree_method="hist",
#     random_state=42,  # Le he puesto random state xd
#     eval_metric="mlogloss",
# )

In [ ]:
# modelo_blackjack.fit(X_train, y_train)

In [ ]:
# from sklearn.metrics import classification_report

# predicciones = modelo_blackjack.predict(X_test)

# nombres_acciones = encoder.classes_

# print(classification_report(y_test, predicciones, target_names=nombres_acciones))

In [ ]:
# import matplotlib.pyplot as plt

# importancias = modelo_blackjack.feature_importances_
# columnas = X.columns

# for col, imp in zip(columnas, importancias):
#     print(f"Columna: {col} -> Importancia: {imp:.4f}")

In [ ]:
# import matplotlib.pyplot as plt
# import pandas as pd

# df_importancias = pd.DataFrame(
#     {"Columna": X.columns, "Importancia": modelo_blackjack.feature_importances_}
# ).sort_values(by="Importancia", ascending=True)

# plt.figure(figsize=(10, 6))
# plt.barh(
#     df_importancias["Columna"],
#     df_importancias["Importancia"],
#     color="royalblue",
# )
# plt.xlabel("Importancia en el modelo")
# plt.title("¿En qué se fija?")
# plt.grid(axis="x", linestyle="--", alpha=0.5)

# plt.show()

In [ ]:
# modelo_blackjack.save_model("modelo_blackjack.json")

In [16]:
import xgboost as xgb

modelo_cargado = xgb.XGBClassifier()

modelo_cargado.load_model("modelo_blackjack.json")

In [17]:
def predecir_accion(
    cartas_jugador,
    dealer_up,
    cards_remaining=200,
    run_count=0,
    true_count=0,
    player_final_action_value=None,
):
    """Recibe tus cartas y te dice la acción óptima según el modelo."""

    # Si no se especifica la suma, la calculamos nosotros sumando la lista
    if player_final_action_value is None:
        player_final_action_value = sum(cartas_jugador)

    # Lista de 8 posiciones rellena de ceros (teníamos 8 cartas)
    vector_cartas = [0] * 8

    # Metemos las cartas en las primeras posiciones
    for i, carta in enumerate(cartas_jugador[:8]):
        vector_cartas[i] = carta

    # Diccionario con todas las columnas que teníamos en el entrenamiento
    datos_jugada = {
        "cards_remaining": [cards_remaining],
        "dealer_up": [dealer_up],
        "player_final_action_value": [player_final_action_value],
        "run_count": [run_count],
        "true_count": [true_count],
    }

    # Añadimos las 8 columnas de las cartas (carta_1, carta_2...)
    for i in range(8):
        datos_jugada[f"carta_{i+1}"] = [vector_cartas[i]]

    # Hacerlo DataFrame
    df_jugada = pd.DataFrame(datos_jugada)

    # Orden de las columnas
    columnas_ordenadas = [
        "cards_remaining",
        "dealer_up",
        "player_final_action_value",
        "run_count",
        "true_count",
    ] + [f"carta_{i+1}" for i in range(8)]
    df_jugada = df_jugada[columnas_ordenadas]

    # Predecir el número de clase
    prediccion_numerica = modelo_cargado.predict(df_jugada)[0]

    # Traducir el número a la letra ('S', 'H', 'P'...)
    accion_recomendada = encoder.inverse_transform([prediccion_numerica])[0]

    # Ver las probabilidades de cada acción
    probabilidades = modelo_cargado.predict_proba(df_jugada)[0]
    mapeo_probs = dict(zip(encoder.classes_, probabilidades))

    print(f"Mano del jugador: {cartas_jugador} (Suma: {player_final_action_value})")
    print(f"Carta visible del Dealer: {dealer_up}")
    print(f"ACCIÓN RECOMENDADA: {accion_recomendada}")
    print(f"Confianza en la decisión: {mapeo_probs[accion_recomendada]*100:.2f}%")

    return accion_recomendada

In [45]:
predecir_accion([2, 4, 10], 6)

Mano del jugador: [2, 4, 10] (Suma: 16)
Carta visible del Dealer: 6
ACCIÓN RECOMENDADA: S
Confianza en la decisión: 99.92%

'S'